#!/bin/bash

# start network manager
sleep 1 && nm-applet &

setxkbmap -option grp:alt_caps_toggle

sleep 1 && idesk &

sleep 1 && volumeicon &

sleep 1 && redshift 
sleep 5 && xrandr --output LVDS-1 --brightness 0.6
